server:  
  port : 8080
spring:
  h2:
    console:
      enabled: true
  main.lazy-initialization: true      
  datasource:
    url: jdbc:h2:mem:mydb  
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        jdbc:        
        '[format_sql]': true
        '[enable_lazy_load_no_trans]': true
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true    
    open-in-view: false
    hibernate:
      ddl-auto: update